### ISSUE TITLE
Belly Pan for 2025 Robot Chassis

### ISSUE THREAD

**Issue by johnthibert** [frc5885/FRC5885Mechanical#10]
Get CAD and place an order for a Lexan belly pan for the 2025 robot

**Comment by marcotron64** [comment]
[2025BellyPan.pdf](https://github.com/user-attachments/files/17334942/2025BellyPan.pdf)

**Comment by johnthibert** [comment]
Belly pan is getting cut out at CenterLine today or tomorrow.
