### ISSUE TITLE
CAD Modelling of New "The Gun" Design

### ISSUE THREAD

**Issue by johnthibert** [frc5885/FRC5885Mechanical#3]
Design the housing of the new driver for BLDC/DC motors

**Comment by zjs0221** [comment]
Does anyone have the model name of "zero to hero"?

**Comment by johnthibert** [comment]
> Does anyone have the model name of "zero to hero"?

@frc5885/mechanical Use the [discussions](https://github.com/frc5885/FRC5885Mechanical/discussions) page for asking questions and talking about ideas

**Comment by h0im3die** [comment]
Barrel extension design is being changed from two halves bolted together with the IO plate glued to the front, too the halves sliding together with the IO plate locking them in place with a quarter turn.

Once a prototype design for the locking mechanism, Il 3d print and modify it until it works as intended.

**Comment by zjs0221** [comment]
Current outline for the new motor controller:

- [ ] Completely handheld
- [ ] Controls two motors
- [ ] Accessible SPARKMAX button
- [ ] Will probably use one slider and one switch per motor
  - Slider for speed and switch for direction (perhaps breaking in neutral position)
- [ ] One index finger button/trigger and one thumb button for turning on (will not operate unless both are pressed) 
  - Consider additional button for left hand use? (in this case it would be trigger + left or right button)

Perhaps something like this:
![Image](https://github.com/user-attachments/assets/c0190f41-d6e0-4972-a9e5-040d5eb9963a)

Any ideas/additions/designs will be greatly appreciated!
